### ISSUE TITLE
Feedback: working with QuantaGrid D51PH-1ULH

### ISSUE THREAD

**Issue by hazilo** [netinvent/ipmi-starter#1]
Quick feedback to say that this tool saved my ass this time!
It is working out of the box with the AST2400 BMC of my QCT D51PH-1ULH from 2015!
Just download the console redirection jviewer.jnlp from the Megarac SP page and run the command as documented: ./javaws.cmd ./jviewer.jnlp

**Comment by deajan** [comment]
Thank you alot for your feedback. I will add your setup to the tested equipment table.
I'm really happy that this tool helped someone, especially when if been in hurry.

Hope the word will spread a bit.

Best regards.

**Comment by hazilo** [comment]
I forgot to add for future reference: it is with the latest BMC firmware version 3.16.00, with the latest BIOS version: 3B04

**Comment by deajan** [comment]
Thanks again for your feedback ;)
Always good to know an effort helped someone.
